
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgBTjkuson4eA0VrfnN8nHBq476cr5gWj9cEoIJKTi3kRA/T8vxQti7xsuz6Hv0HmLNVtKqRP++XTgCVBnDxkZaalCHjOXHlUcRtPHT4/cfDAFI7eKVGq8VnGAWFfba3M1wYSe+Uv4xsm4b6ffjityP2gyuVhrzY3GhTvDLd4pQINt6/CflII+oyIiAXNJxY5Q0m+8AUhZdqhYmhGZaifuI90Q7KfiqDK7YXQ6jj8Nc26gChju5dNlx7rPFLqVMMAiw2U68Mbv7eW5u4JLKyPCwgvO61YpPX/lJjYSMitsGHZvz1HhDw6n1umKEwKKVqIMbi9t4GYmcA66iMohQPlJtR6GMbtEOcygL9dIzJCoBnpziAOzKC6x6XgmpEejvgH6NefnYzCmOnskiIY0CzbwI6aQaEIKSwSKWRpZXMN362H+VxUrQi9r9yAqb8pC+35Fyg8M+hh90BQLS7P3WtUlOBtlfp9TKDeAxW5YKI1/MyovkWN/+/OyEMaKLrgwlyu4Tva6z5C3ueaAuR9N2T2MXpVsbZ0cs9BiVkI1rGNWDQ6pco0SiCja17KY8DgUdytQvVTIb47qw/TvgTs6FWmgeG+yokn2EvxZVIYQ1fyp95/UVSn57YqjGPKSJEzQebfkg4MBbCrSHDoWezNvvS0rpsIEMqrrg5QAVVY/cjMRHYeBU0JwEGvvVWehZWkVV0p1Y5SURFWJCdeJuaHL1kapzxFv8HNuVMPxh5bG5Ze/HZGso=
    password: AgBu3a5+EwhqZVQ9csNmOuYwtN7nSV7Af2lhYVhcHk1nWynEwfa28U3boKCIDSgcVY0UPth4UclafyRB5C7rXdYrUv/gXtP/mYgznT0ehKlFIFyuGUyiY1V0xC2rLsSnjmM5V1pYpc+3hBMlBunqav+CY4NeeFs0MIML6g+tJQaI8qj03i131rj9+Qf0wqPCvlRNqw1nYqdr1ixyyxYQ1SOB2xgoXpRPMCNUKQHNKpmgbSqf3LvyUdY4wd1BEDEiLKCBuCXL+sTL22jMLX+VuOshaEC2vwy1lLFheB/eYjAfHc++GIGzf7FaWoLiejy0NIQZyuvnCXGzBn+HAw0mG/qbjC2pWkcRlz+yYPKxJ/3YadTPe9ovnCLwHQEFlaIdBKJxe9LJN6/3YBWOqd
